# Generated by Django 4.2.11 on 2024-04-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الصف الدراسي')),
            ],
            options={
                'verbose_name_plural': '03_class_level',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='المنهج الدراسي')),
            ],
            options={
                'verbose_name_plural': '04_curriculum',
            },
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='المرحلة الدراسية')),
            ],
            options={
                'verbose_name_plural': '02_educational_level',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='رقم البطاقة')),
                ('security_code', models.CharField(max_length=3, verbose_name='رمز الحماية')),
                ('expiration_date', models.CharField(max_length=10, verbose_name='تاريخ انتهاء الصلاحية')),
                ('card_name', models.CharField(max_length=100, verbose_name='الاسم على البطاقة')),
            ],
            options={
                'verbose_name_plural': '16_payment',
            },
        ),
        migrations.CreateModel(
            name='SessionDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='مدة الحصة الواحدة')),
            ],
            options={
                'verbose_name_plural': '13_session_duration',
            },
        ),
        migrations.CreateModel(
            name='SessionFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عدد الحصص الأسبوعية')),
            ],
            options={
                'verbose_name_plural': '12_session_frequency',
            },
        ),
        migrations.CreateModel(
            name='StudentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '08_student_count',
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '09_study_goal',
            },
        ),
        migrations.CreateModel(
            name='StudySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitable_day', models.CharField(choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الأثنين', 'الأثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=100, verbose_name='اليوم المناسب')),
                ('time_period', models.CharField(choices=[('الفترة الصباحية', 'الفترة الصباحية'), ('الفترة المسائية', 'الفترة المسائية')], max_length=100, verbose_name='الفترة الزمنية المناسبة')),
                ('suitable_timing', models.CharField(choices=[('12:00', '12:00'), ('15:00', '15:00')], max_length=100, verbose_name='التوقيت المناسب')),
            ],
            options={
                'verbose_name_plural': '11_study_schedule',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/subject_images/')),
            ],
            options={
                'verbose_name_plural': '06_subject',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع الاشتراك')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الخصم')),
                ('duration', models.CharField(max_length=50, verbose_name='المدة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر')),
            ],
            options={
                'verbose_name_plural': '14_subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sessionduration', verbose_name='مدة الحصة الواحدة')),
                ('session_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sessionfrequency', verbose_name='عدد الحصص الأسبوعية')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.subscriptionplan', verbose_name='نوع الاشتراك')),
            ],
            options={
                'verbose_name_plural': '15_subscription',
            },
        ),
        migrations.CreateModel(
            name='SubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ManyToManyField(to='setup.subject')),
            ],
            options={
                'verbose_name_plural': '07_subject_selection',
            },
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=10, verbose_name='النوع')),
                ('nationality', models.CharField(max_length=100, verbose_name='الجنسية')),
                ('whatsapp_number', models.CharField(max_length=100, verbose_name='رقم الواتساب')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('difficulties', models.BooleanField(verbose_name='هل تواجه اي صعوبات في الدراسة؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('suitable_day', models.CharField(choices=[('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الأثنين', 'الأثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة')], max_length=100, verbose_name='اليوم المناسب')),
                ('time_period', models.CharField(choices=[('الفترة الصباحية', 'الفترة الصباحية'), ('الفترة المسائية', 'الفترة المسائية')], max_length=100, verbose_name='الفترة الزمنية المناسبة')),
                ('suitable_timing', models.CharField(choices=[('12:00', '12:00'), ('15:00', '15:00')], max_length=100, verbose_name='التوقيت المناسب')),
                ('card_number', models.CharField(max_length=16, verbose_name='رقم البطاقة')),
                ('security_code', models.CharField(max_length=3, verbose_name='رمز الحماية')),
                ('expiration_date', models.CharField(max_length=10, verbose_name='تاريخ انتهاء الصلاحية')),
                ('card_name', models.CharField(max_length=100, verbose_name='الاسم على البطاقة')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.classlevel', verbose_name='الصف الدراسي')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.curriculum', verbose_name='المنهج الدراسي')),
                ('educational_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.educationallevel', verbose_name='المرحلة الدراسية')),
                ('goals', models.ManyToManyField(to='setup.studygoal', verbose_name='أهداف الدراسة')),
                ('session_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sessionduration', verbose_name='مدة الحصة الواحدة')),
                ('session_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sessionfrequency', verbose_name='عدد الحصص الأسبوعية')),
                ('student_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.studentcount', verbose_name='عدد الطلاب')),
                ('subjects', models.ManyToManyField(to='setup.subject', verbose_name='المواد')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.subscriptionplan', verbose_name='نوع الاشتراك')),
            ],
            options={
                'verbose_name_plural': '17_student_application',
            },
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.classlevel', verbose_name='الصف الدراسي')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.curriculum', verbose_name='المنهج الدراسي')),
                ('educational_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setup.educationallevel', verbose_name='المرحلة الدراسية')),
            ],
            options={
                'verbose_name_plural': '05_education_info',
            },
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.ManyToManyField(to='setup.studygoal', verbose_name='أهداف الدراسة')),
                ('student_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.studentcount', verbose_name='عدد الطلاب')),
            ],
            options={
                'verbose_name_plural': '10_additional_info',
            },
        ),
    ]
