# Generated by Django 4.2.11 on 2024-04-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_suitabletiming_alter_studyschedule_suitable_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyschedule',
            name='suitable_day',
            field=models.CharField(max_length=100, verbose_name='اليوم المناسب'),
        ),
        migrations.AlterField(
            model_name='studyschedule',
            name='time_period',
            field=models.CharField(max_length=100, verbose_name='الفترة الزمنية المناسبة'),
        ),
    ]
