# Generated by Django 4.2.11 on 2024-04-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_studyschedule_suitable_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='suitable_day',
            field=models.CharField(max_length=100, verbose_name='اليوم المناسب'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='suitable_timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.suitabletiming', verbose_name='التوقيت المناسب'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='time_period',
            field=models.CharField(max_length=100, verbose_name='الفترة الزمنية المناسبة'),
        ),
    ]
