# Generated by Django 4.2.11 on 2024-04-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_alter_studentapplication_suitable_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم اليوم')),
            ],
            options={
                'verbose_name_plural': '11_day',
            },
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='suitable_day',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='suitable_day',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='suitable_day',
            field=models.ManyToManyField(to='setup.day', verbose_name='الأيام المناسبة'),
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='suitable_day',
            field=models.ManyToManyField(to='setup.day', verbose_name='الأيام المناسبة'),
        ),
    ]
