# Generated by Django 4.2.11 on 2024-04-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_day_remove_studentapplication_suitable_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='student_count',
        ),
        migrations.RemoveField(
            model_name='educationinfo',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='educationinfo',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='educationinfo',
            name='educational_level',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='suitable_day',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='suitable_timing',
        ),
        migrations.RemoveField(
            model_name='subjectselection',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='session_duration',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='session_frequency',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_plan',
        ),
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
        migrations.DeleteModel(
            name='EducationInfo',
        ),
        migrations.DeleteModel(
            name='StudySchedule',
        ),
        migrations.DeleteModel(
            name='SubjectSelection',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
