# Generated by Django 4.2.11 on 2024-04-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
