# Generated by Django 4.2.11 on 2024-04-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_remove_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name_plural': '00_custom_users'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_images/'),
        ),
    ]
