# Generated by Django 4.2.11 on 2024-04-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_alter_customuser_options_alter_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='security_code',
            field=models.CharField(max_length=20, verbose_name='رمز الحماية'),
        ),
    ]
