# Generated by Django 4.2.11 on 2024-04-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_alter_studentapplication_security_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlevel',
            options={'verbose_name_plural': '02_class_level'},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name_plural': '03_curriculum'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name_plural': '07_day'},
        ),
        migrations.AlterModelOptions(
            name='educationallevel',
            options={'verbose_name_plural': '01_educational_level'},
        ),
        migrations.AlterModelOptions(
            name='sessionduration',
            options={'verbose_name_plural': '10_session_duration'},
        ),
        migrations.AlterModelOptions(
            name='sessionfrequency',
            options={'verbose_name_plural': '09_session_frequency'},
        ),
        migrations.AlterModelOptions(
            name='studentapplication',
            options={'verbose_name_plural': '12_student_application'},
        ),
        migrations.AlterModelOptions(
            name='studentcount',
            options={'verbose_name_plural': '05_student_count'},
        ),
        migrations.AlterModelOptions(
            name='studygoal',
            options={'verbose_name_plural': '06_study_goal'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': '04_subject'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name_plural': '11_subscription_plan'},
        ),
        migrations.AlterModelOptions(
            name='suitabletiming',
            options={'verbose_name_plural': '08_suitable_timing'},
        ),
    ]
